#!/usr/bin/env python3
import os
from os.path import basename
import fnmatch
from glob import glob
import sys
import re
import argparse
import os
import itertools
class colors:
    FAIL = '\033[91m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    BLUE = '\033[94m'
    HEADER = '\033[95m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    @staticmethod
    def color(str, color):
        if not args.no_colors:
            return "%s%s%s" % (color, str, colors.ENDC)
        else:
            return str
    @staticmethod
    def color_se(str, start, end):
        if not args.no_colors: 
             return "%s%s%s" % (start, str, end)
        else:
             return str

TODO_COLOR = colors.BLUE
BUG_COLOR = colors.FAIL
XXX_COLOR = colors.WARNING
search_pattern = re.compile(r"(TODO|FIXME|FIX|BUG|XXX): (.*)")

def get_all_files(directory, pattern, exclude):
    files = [os.path.join(dirpath, f)
        for dirpath, dirnames, files in os.walk(directory) if not any(map(dirpath.startswith, exclude))
        for f in itertools.chain.from_iterable([fnmatch.filter(files, x) for x in  pattern])]
    return files

def build_search_pattern(list):
    list = [t.upper() for t in list]
    str = r"("
    first = True
    for pattern in list:
        if first:
            str += (pattern)
            first = False
        else:
            str += "|" + (pattern)
    str += r"): (.*)"
    return re.compile(str)

def find_tasks_in_file(file):
    line_cnt = 0
    tasks = []
    with open(file) as f:
        if args.verbose == 2:
            print(colors.color("Scanning %s for tasks... " %file,colors.HEADER), end='')
        try:
            for line in f:
                line_cnt += 1
                line = search_pattern.search(line)
                if line is not None:
                    tasks.append((line.group(1), line_cnt, line.group(2).strip("*/")))
        except:
            pass
    if args.verbose == 2:
        if(len(tasks)>0):
            print(colors.color("found %d tasks."% len(tasks), colors.GREEN))
        else:
            print(colors.color("found 0 tasks.", colors.HEADER))
    return tasks
def get_stats(tasks):
    bugs = len([t for t in tasks if t[0] in ["BUG", "FIXME", "FIX"]])
    todos = len([t for t in tasks if t[0] == "TODO"])
    xxx = len([t for t in tasks if t[0] == "XXX"])
    return (todos, bugs,xxx)

def color_output(no_color): return (not no_color and sys.stdout.isatty())

def get_all_tasks(directory, pattern,exclude):
    files = get_all_files(directory,pattern,exclude)
    tasks = {}
    for file in files:
        t = find_tasks_in_file(file)
        if t != []:
            tasks[file] = t

    if args.verbose >= 1:
        task_cnt = sum([len(t[1]) for t in tasks.items()])
        print(colors.color("Found %d tasks in %d files!" % (task_cnt, len(tasks)), colors.GREEN));
    return tasks

def print_stats(stats):
    print(colors.color("Summary", colors.HEADER))
    todo_str = "Todos: "+ colors.color("%d"%stats[0],TODO_COLOR)
    bug_str = "Bugs: "+ colors.color("%d"%stats[1], BUG_COLOR)
    xxx_str = "Unclear: "+ colors.color("%d"%stats[2], XXX_COLOR)
    print (todo_str + ", " + bug_str + ", " + xxx_str)

def get_stat_header(stats):
    stat_str = "(Todos: %s" % colors.color_se("%d"%stats[0],TODO_COLOR, colors.HEADER)
    stat_str += ", Bugs: %s" %  colors.color_se("%d"%stats[1], BUG_COLOR, colors.HEADER)
    stat_str += ", Unclear: %s) " % colors.color_se("%d"%stats[2], XXX_COLOR, colors.HEADER)
    return stat_str

def decorate_task(task):
    color = ""
    if task in ["BUG", "FIX", "FIXME"]:
        color = BUG_COLOR
    elif task in ["XXX"]:
        color = XXX_COLOR
    else:
        color = TODO_COLOR
    return colors.color("%-7s" %task, color)
def print_tasks(file_tasks):
    overall_todos, overall_bugs, overall_xxx = (0,0,0)
    for file,tasks in file_tasks.items():
        (todos,bugs,xxx) = get_stats(tasks)
        if args.total:
             overall_todos += todos
             overall_bugs += bugs
             overall_xxx += xxx

        stat_str = get_stat_header((todos,bugs,xxx))
        file_str =  " File " + file + " "
        file_str = colors.color_se(file_str,colors.BLUE,colors.HEADER)
        file_str += stat_str;
        if color_output(args.no_colors):
            print(colors.color(file_str.center(width+25,"="), colors.HEADER))
        else:
            print(colors.color(file_str.center(72,"="), colors.HEADER))
        
        print (colors.color("%-7s %-5s %s" % ("Type","Line","Comment"), colors.HEADER))
        for task in tasks:
            task_type, line, comment = task
            task_type = decorate_task(task_type)
            print("%s %-5d %s" % (task_type, line, comment))
        print()
    return (overall_todos, overall_bugs, overall_xxx)

def print_summary(file_tasks):
    tasks = [t[1] for t in file_tasks.items()]
    all_tasks = []
    for file_task in tasks:
        for task in file_task:
            all_tasks.append(task)
    if len(all_tasks) > 0:
        if color_output(args.no_colors):
            print (colors.color(" Summary ".center(width-15, "="), colors.HEADER))
        else:
            print (colors.color(" Summary ".center(72, "="), colors.HEADER))
        print (colors.color("%-7s %s" % ("Type","Comment"), colors.HEADER))
    for task in all_tasks:
        task_type, _, comment = task
        task_type = decorate_task(task_type)
        print("%s %s" % (task_type, comment))
    overall_todos, overall_bugs, overall_xxx = get_stats(all_tasks)
    print()
    return (overall_todos, overall_bugs, overall_xxx)

if __name__ == "__main__":
    parser = argparse.ArgumentParser();
    parser.add_argument("-n","--no-colors", action="store_true", help="Disable ANSI-Color-Sequences")
    parser.add_argument("-p", "--pattern", default=["*.c", "*.h", "*.S"], help="Search patterns", action="append")
    parser.add_argument("-i", "--todo-name", help="Only seek for this todo names", action="append")
    parser.add_argument("-e","--exclude", default=["./.git"], help="Exclude directories", action="append")
    parser.add_argument("-t", "--total", action="store_true", help="Enable overall stats")
    parser.add_argument("-s","--summary", action="store_true", help="Just give me a list of tasks")
    parser.add_argument("-v", "--verbose", default=0,action="count", help="Increase verbosity")
    parser.add_argument("dir", default=".", nargs="?", help="Specify search directory")
    args = parser.parse_args();

    if args.todo_name is not None:
        search_pattern = build_search_pattern(args.todo_name); 

    if sys.stdout.isatty():
        width = os.get_terminal_size().columns

    file_tasks =  get_all_tasks(args.dir, args.pattern, args.exclude)
    if not args.summary:
        total = print_tasks(file_tasks)
    else:
       total = print_summary(file_tasks)
    if args.total:
        print_stats(total)
